export const vierzehn  = [
    {Title: "Meetup in Kambodscha"},
    {Text: "Das Ende vom letzten Eintrag hat es nicht online geschafft. Da ich sicherheitshalber auch keine lokale Kopie aufbewahrt habe, sind die letzten Tage Vietnam leider für immer im Datenether verschwunden. Hervorragende Tage in einem Luxusressort am Arsch der Heide und ein schöner Abend mit Bekanntschaften in Hanoi bleiben damit meiner mit größer werdendem zeitlichen Abstand stetig weiter romantisierenden Erinnerung überlassen und konnten sich der kalten Tristesse eines schlecht geschrieben Erfahrungsberichts in einem nahezu toten Blog im Internet entziehen. "},
    {ImageS: "Katzenbilder, um die Klickzahlen zu pushen"},
    {Text: "Fast komplikationsfrei (habe ich mich bei meinem Vietnamaufenthalt doch tatsächlich um einen Tag verrechnet…) flog ich im Anschluss nach Phnom Peng. Dort traf ich auf Ella & Ali, Karsten und Max. Dori & Flori (selbst meine Rechtschreiberkennung kann das kaum auf sich sitzen lassen und möchte die ganze Zeit „Flora“ forcieren), die wunderbaren Organisatoren dieses Trips, trafen wir erst einen Tag später in Siem Reap. Flo lebt derzeit in Kambodscha, weswegen sich in dort eine Hamburger Crew mit leichten Einschlägen aus Köln und Münster einfinden konnte, um von seinen Ortskenntnissen profitierend ihren Urlaub zu genießen. "},
    {ImageH: "Ali musste das Foto machen"},
    {Text: "Die Hauptstadt ließen wir aber wie gesagt bereits am ersten Tag hinter uns, um uns der bekanntesten Sehenswürdigkeit des Landes zuzuwenden - Anker Wat, also mal wieder Tempel. Selbst ein Ignorant wie ich muss aber eingestehen, dass die es durchaus in sich hatten. Dass wir die Anlage im Rahmen einer Fahrradtour auf Mountainbikes (die allerdings auch dringend notwendig waren in der Regenzeit) eroberten, tat dem ganzen definitiv keinen Abbruch. Das Rahmenprogramm bestand aus lottern am Pool, gemütlichen Schnacks und fantastischem Essen. Alles was das Herz begehrt - zumindest meins."},
    {ImageS: "Näseln mit Königen"},
    {Text: "Im Anschluss brachte uns der Nachtbus in den Süden des Landes. Unsere Unterkunft dort war direkt am Fluss gelegen. Neben Kajakfahren konnte man dort fantastisch mit dem Roller das hügelige Umland erkunden. Den Fotos der Anderen nach zu urteilen, muss das ganz fantastisch gewesen sein. Eigentlich zu meiner Scham muss ich gestehen, dass ich diese Gelegenheit sausen ließ, um meinen Tag lieber in einem Spa im skandinavischen Stil betrieben von zwei Kanadiern verbrachte. Dass besagte Scham ob des Vergnügens von Sauna und Massagen bis heute ausbleibt, sagt so gut wie nichts über Kambodscha, ein wenig über schwedische Saunakultur, Gutes über die kanadischen Besitzer und vermutlich am meisten über mich."},
    {ImageS: "Besagte Hügel, die ich leider nur von meiner Liege aus und nicht vom Nahen auf dem Roller begutachten konnte"},
    {Text: "Zum Abschluss gönnten wir uns dann noch ein kleines Abenteuer auf der Insel Koh Rong. Die bereits spannende Anreise, zu der auch gehörte, dass das letzte Stück schwimmend zurückgelegt wurde, bereite einen Vorgeschmack auf ein paar Tage ohne fließend Wasser, Solarstrom und wechselhaften (wenig bis gar keinen) Empfang. Fledermausattacken, Schlangenphobien, Mückeninvasionen (meine grandiose Thailandstatistik wurde ruiniert. Und das lag nicht am Mangel von Garnelen) und verschollene Betreiber strapazierten Nerven. Das war aber nichts, was ein BBQ mit gegrilltem Fisch am Lagerfeuer, leuchtendes Iron-Man-Style-Baden in Plankton nach dem Sonnenuntergang oder der Besuch eines sehr rudimentären Dorfes der Inselbewohner nicht auffangen konnten."},
    {ImageS: "Besagtes Dörfchen"},
    {Text: "Dass das Meer dort Ende Oktober entspannte 30 Grad hat, schadete selbstverständlich auch nicht. Sogar Robinson-Crusoe-anmutende Selbstversorger-Versuche waren von Erfolg gekrönt. Ich war zugegeben aber nur beim verspeisen des Fisches nützlich und nicht beim Fangen. Außerdem wissen wir nun, dass zwei Babykatzen mehr als genug sind, eine ganze Gruppe langfristig bei Stange zu halten, dass Karsten beim Schwimmen im Ozean noch besser ist als im gleichnamigen Kartenspiel und kennen jedes französische Schimpfwort."},
    {ImageH: "El Capitano"},
    {Text: "Aber auch diese schöne Zeit musste vorbeigehen und während die anderen in Ellas Geburtstags hineinfeierten - Herzlichen Glückwunsch nachträglich an dieser (machen wir uns nichts vor) sehr privaten Stelle! -, war ich bereits im Flughafenhotel, um die nächste Etappe einzuleiten. An dieser Stelle noch einmal vielen Dank an die Gruppe, dass ich mich für diese fantastische Zeit bei euch einklinken durfte und insbesondere an Dori und Flo, deren exzellente Planung einen reibungslosen, mit Highlights bespickten Ablauf ermöglichten. Auf ein baldiges Wiedersehen in Deutschland oder erneut in Asien."},
    {ImageH: "Irgendwas über Freundschaft, Natur und das Überwinden aller Widerstände"},
    {Text: "PS: Im Flugzeug gab es unter Anderem den vierten Teil von Matrix. Was zum Henker soll sowas? Einfach alles an dem Film ist scheiße. Da gibt es rein gar nichts schön zu reden."}
]