export const zwei = [
    {Title: 'Raus aus Bangkok'},
    {Text: 'React lässt immernoch auf sich warten, weil das Ganze doch einen ganz schönen Rattenschwanz mit sich bringt, aber auch weil ich die Tage anders besser nutzen konnte.'},
    {Text: 'Chinatown hinterlies einen etwas faden Beigeschmack und einen furchtbaren Hauptgeschmack, aber das einzige street-food dort, welches wir zu uns nahmen, war entgegen Jonas´ Einschätzung gruselig. Abführmittel hätte den gleichen Effekt gehabt, vermutlich aber besser geschmeckt. Bevor wir ins Zentrum (was auch immer das beudetet in Bangkok) umgezogen sind, verbrachten wir noch einen Tag damit, zu versuchen das Portugiesenviertel anzuschauen. Der Versuch scheiterte. Wir haben es nicht gefunden.'},
    {Text: 'Die beiden folgenden Tage im Zentrum waren interessant. Deutschlands bekannte Einkaufsstraßen, die in jeder Stadt gleich aussehen, gibt es in Bangkok auch. Allerdings befindet sich alles in einer einzigen Mall und es gibt richtig viele davon. Selten so viele Dinge, die ich nicht kaufen wollte an einem Ort gesehen, aber man konnte dort gut essen. Außerdem waren wir noch auf dem King Power Manahakon (großartiger Name) dem höchsten SkyWalk in Thailand mit 316m. Es stellte sich heraus, dass das für mich in etwa 300m zu hoch ist. Jonny hatte aber seinen Spaß und gewann ein halbes Bier, weil ich mich aus Rücksicht auf meine Nerven schnell von der Dachterasse zurückziehen musste. Der Ausblick war allerdings phänomenal. Bei Tag wurde die Weitläufigkeit und bei Nacht das Chaos der Stadt perfekt eingefangen.'},
    {ImageS: 'Bangkok von oben'},
    {Text: 'Danach begann unsere Tour de force nach Koh Tao. Für die Reise pickten wir uns den Nachtbus heraus. Da wir den Tag über etwas Downtime hatten, haben wir uns mit Cocktails vorbereitet. Die Fahrt an sich war eigentlich ganz angenehm, abgesehen von den Tatsachen, dass das am Bus selbst groß angepriesene Wifi nonexistent war und ich wie immer in Allem, was sich bewegt, nicht schlafen konnte. Nach der Ankunft am nächsten Morgen verließen wir das Festland dann per Schnellfähre.'},
    {ImageS: 'Adieu Festland'},
    {Text: 'Um meinen Schlafrhythmus nicht vollständig zu ruinieren, wollte ich tagsüber wach bleiben. Dafür fasste ich im Wesentlichen zwei Pläne: Bier & Aktivität. Aufgrund der gerade Nachmittags knallenden Sonne musste allerdings schnell mindestens eine Maßnahmen fallengelassen werden. Aus diesem Grund blieb die Erkundung der Insel vorerst auf einen kleineren Teil beschränkt und die Erklimmung eines der vermutlich aufregenderen Aussichtspunkte von Koh Tao verschoben, aber nicht aufgegeben. Ansonsten scheint das hier ein ziemliches Taucherparadies zu sein. Jeder zweite Laden möchte einem diese Kunst näher bringen und wir sahen bereits diverse Gruppen in See stechen. Party wird auch nicht zu klein geschrieben. Jonny bestätigte, dass es Abends auch unter unserem Hostel heiß herging. Mich ließ das freilich nach 35h wachen Stunden reichlich unbeeindruckt.'},

];