export const sieben = [
    {Title: 'Die letzte Woche Thailand'},
    {Text: '...und was für eine. Vermutlich haben wir es mit dem Part der "mental" war im Vergleich zum "wholesome Stuff", wie sich unser ganz fantastischer Host auszudrücken pflegte, etwas übertrieben, aber Ko Phi Phi war ein schöner Abschluss von Kapitel 1.'},
    {Text: 'Nachdem uns der Reisetag mal wieder ziemlich geplätet hatte, sind wir Samstag langsam gestartet und haben uns einen schönen Strandtag am Long Beach gemacht; angeblich der schönste Strand der Insel. Die Unterschiede liegen aber im Detail. Immerhin war wenig los und das Wasser wie erhofft endlich mal eine Abkühlung. Dummerweise haben wir uns im Anschluss vom Nachtleben der Insel etwas verführen lassen. Das war an dem Abend ganz nett, aber Sonntag fiel entsprechend überschaubar aus. Montag haben wir uns dann so richtig die Insel angeguckt. Darunter viel die Erkundung einer traumhaften Bucht mit dem wirklich schönsten Strand der Insel. Leider konnte man dort nicht richtig baden, außer man ließ sich wie ich nicht davon abhalten, dass einem scharfkantige Felsen die Füße zerschnitten. Nach dem Mittagessen auf der Südseite und kleiner Dschungelwanderung haben wir dann noch die durchaus spektakulären Aussichtspunkte der Insel abgeklappert.'},
    {ImageS: 'Ko Phi Phi von oben'},
    {Text: 'Verzückt von einem produktiven Tag ließen wir uns im Anschluss direkt wieder vom Nachtleben einnehmen. Beer-Pong und Buckets (4€ für einen kleinen Eimer Schnapps. Echt nicht gesund, aber das Preis-/Leistungsverhältnis...) brachten uns in die richtige Stimmung die Fight-Night zu genießen. Bei dieser kongenialen Veranstaltung dürfen sich Touristen gegenseitig auf die Mappe hauen. Verständlicherweise waren wir begeisterte Zuschauer. Erst recht als klar wurde, dass das Angebot regen Zuspruch fand. Abgesehen von einigen Ausnahmen hatten es die meisten Akteure allerdings ganz schön drauf. Da das aber nicht immer so war, wurden wir auch Zeugen eines saftigen KO´s. "Ich wollte ihn eigentlich erstmal nur testen...", gestand der Kampferfahrene der beiden Kontrahenten, nachdem er seinen Gegner mit einem Highkick an die Schläfe direkt mit der ersten Aktion des Kampfes ausnockte. Der andere Dude war kurz wegtreten und hatte dann sogar noch eine ziemlich ausgemachte Zitterattacke, was kurz ein wenig aufregend war. Ein kleiner Orientierungstest im Anschluss ergab aber, dass er seine Sinne noch zusammen hatte und seinem Kopf nichts dramatischeres angetan wurde als der Bucket, den es im Anschluss als Belohnung für die Teilnahme gab, nicht deutlich schlimmer konnte.'},
    {Text: 'Dienstag war logischerweise wieder überschaubar. Mehr als ein Strandbesuch war nicht drin, aber im Urlaub langt das ja auch in der Regel. So haben wir es dann erst einen Tag vor Abreise geschafft, eine von den Bootstouren auf die Nachbarinsel einzustreuen. Da gab es Affen zu sehen, Buchten zu bestaunen und man konnte mit haufenweise Fischen schnorcheln. Vor Allem war aber wieder jede Menge bootsfahren inklusive, was auf einem Ozean durchas spaßig sein kann.'},
    {ImageS: 'Affentheater'},
    {Text: 'Heute sind wir nach Phuket rübergefahren von wo aus wir morgen nach Singapur weiterfliegen. Unsere Zeit in Thailand endet damit und es lohnt sich zu resümieren. Thailand ist ein wirklich schönes Land mit vielen tollen Inseln und großen Nationalparks, die alle einen Besuch wert sind. Das Essen ist wie bereits erwähnt ganz fantastisch und Bangkok ist sicherlich speziell, hat aber auch viel zu bieten. Zu Thailändern lässt sich wenig sagen, weil sie aus ihrer Rolle als "Gastgeber" eigentlich nie rauskommen. Das einzige persönliche Gespräch hatten wir in Bangkok. Er hat sich mit uns unterhalten, weil er Europäer als offener und unkomplizierter empfindet. Diese Einschätzung teilen sicherlich nicht alle, aber mit Offenheit sind wir sicherlich nicht überschüttet worden. Stattdessen hängt man dan die meiste Zeit mit anderen Europäern oder Amerikanern ab - vorrangig Briten, Deutschen, Holländern und Franzosen (die bleiben natürlich unter sich). Insgesamt ist Thailand eine gigantische Tourismus-Maschinerie, in der man bewaffnet mit dem obligatorischen Reisesticker auf der Brust kaum verloren gehen kann und von Hostelhaustür zu Hostelhaustür kutschiert wird. Wenig überraschend ähnelten sich viele Reiserouten stark und man traf bekannte Gesichter von früheren Stops im Verlauf der Zeit immer wieder. Jonny und ich waren uns eigentlich recht einig, dass Thailand eine gute Erfahrung war, aber diese so schnell auch nicht wiederholt werden muss. Wer es super findet, in seinem Urlaub durchgehend bespaßt zu werden und ohne Mühe zu reisen, ist in Thailand aber genau richtig. Weitere lose Erkenntnisse und Errungenschaften:'},
    {Liste: [
        'Auf rot folgt nicht braun.',
        'Die Vorgabe mehr Shrimps zu essen als Mückenstiche zu bekommen wurde gemeistert: 369 zu 364.',
        'Bis jetzt kommen wir auf eine angemessene Zahl Bootsfahrten.',
        'Klimaanlagen sind eine der wichtigsten Erfindungen der Menschheitsgeschichte.',
        'Anti-Brumm auch.',
        'Auf rot folgt immernoch nicht braun.',
        '100 Liegenstütze am Tag sind für Jonny gar kein Thema.',
        'Bargeld ist unnötiger, nerviger Dreck.'
    ]},
    {ImageS: 'Maya Bay - jaja, der shit von The Beach'}
];