export const acht = [
    {Title: 'Singapur und so'},
    {Text: 'Der durchaus sinnvolle Hinweis, dass es gar nicht so schlecht wäre, die Bilder auch in Orginalgröße ansehen zu können, hat es nun auf die Seite geschafft. Die grundsätzliche Idee den Blog mit verschiedenen Features aufzufrischen besteht auch nach wie vor, aber die Wahrheit ist, dass ich vor lauter Urlaub einfach zu nichts komme. Das wird sich in den kommenden Wochen/Monaten hoffentlich noch ändern, wenn die Intensität etwas runtergeschraubt wird. Meine Lieblingsserie "Ghost in the Shell:SAC" (vermutlich zumindest, auch wenn "Legion" dicht folgt. Eine Serie, die irgendwie noch niemand gesehen hat, trotz diverser Werbekampagnen meinerseits mit dem Ziel, das unters Volk zu bringen.)'},
    {Link: "https://www.youtube.com/watch?v=7niEY7h5Q2c",
     Text: "Alleine der Soundtrack ist es schon wert"
    },
    {Text: 'zeichnet neben großartiger Story auch aus, dass sie bereits vor fast 20 Jahren die Idee von UX (user experience) in meiner Meinung nach großartiger Voraussicht eingefangen hat. Die Verbindung mit dem Internet ist ein "Eintauchen" in den digitalen Raum, der die analoge Welt eins zu eins spiegelt. Die Bedienung wird damit vollständig intiutiv und die vollständige Abtraktion vom zugrundeliegenden Code ist vollzogen. Das ist eine Vision, deren erste Ausläufer vermutlich bereits zu meinen Lebzeiten am Horizont zu erkennen sein werden und die ein aufregendes und erschreckendes Versprechen der Zukunft an uns darstellen; mit all den wilden Implikationen zur Identität (oder ihrer Auflösung im Kollektiv) oder Unsterblichkeit die dazugehören. Die zugrundeliegende Sprache in Ansätzen erahnen zu können, ist eine Idee, die mich genügend fasziniert, um dieses Projekt nicht abzuschreiben.'},
    {ImageH: 'Rennen gewonnen. Rematch verweigert. Like a boss.'},
    {Text: 'Singapur war abgefahren. Die definitiv sehr reiche Stadt bietet einiges, von dem deutsche Großstädte viel lernen könnten. Das beginnt bereits beim öffentlichen Verkehr. Ein dichtes Metro-Netz autonomer Züge lässt einen nahezu alles in Singapur schnell erreichen. Die Bahnen fahren im 3 - 4 Minuten Takt. Wartezeiten gibt es dementsprechend kaum und wenn etwas mal doch abseits liegt, fängt einen das umfangreiche Busnetz problemlos auf. Der Clou ist allerdings, dass dieses gesamte Angebot jederzeit mit Kreditkarte benutzt werden kann. Check-In und Check-Out werden so festgehalten und das Zeitintervall in Rechnung gestellt. Kein idiotischer Papiermüll, kein Erlernen der Ticketstruktur und sowieso kein Bargeld - es kann so  einfach sein. Nach fünf Tagen Singapur habe ich ohnehin nur eine ungefähre Vorstellung wie die Dollarnoten eigentlich aussehen. Bargeld ist nicht notwendig. Folge des hervorrangenden öffentlichen Netzes zu für die örtlichen Verhältnisse sehr fairen Preisen, ist ein verhältnismäßig akzeptables Niveau von Autoverkehr - zumindest für das Niveau asiatischer Großstädte nach meinen sehr überschaubaren Erfahrungen. Selbstverständlich sieht man nach wie vor noch viel zu viele von den Mistdingern und während die Situation für Füßgänger besser ist als in Bangkok (das heißt: Fußwege sind existent), haben es Fahrradfahrer nicht leicht. Andererseits lese ich dann, dass die vermutlich einzige größere Maßnahme für soziale Gerechtigkeit der letzten Zeit in Deutschland in Form des 9€ Tickets wohl nicht verlängert wird und könnte schon wieder...; aber lassen wir das.'},
    {Text: 'Ein weiteres Plus ist, wie grün die Stadt ist. Riesige Parkanlagen, die teilweise schon fast Regenwald-Flair vermitteln sind keine Ausnahme.'},
    {ImageH: 'Warum ist denn eigentlich immer alles so hoch?'},
    {Text: 'Selbstverständlich gehören zum bekannten Marina Bay Komplex auch die Marina Bay Gardens und vertical gardening ist ein riesen Ding. Dementsprechend ist das Klima auch deutlich erträglicher als in der drückenden urbanen Dystopie Bangkok. Das mag allerdings auch ein wenig mit einer gewissen Gewöhnung unsererseits zusammenhängen.'},
    {Text: 'Der überschwengliche Reichtum zeigt sich unter Anderem auch auf der Erholungsinsel Sentosa. Dieses künstliche Strandparadies mitten in einem riesigen Industriehafen bietet eine Oase von Badespaß und allen möglichen Aktivitäten von Zip-Lining bis Bungee Jumping. Die Strände und gefühlt alle 10 Meter installierte Sanitäranlagen mit Duschen und Umkleideräumen dürfen gratis genutzt werden. Gelegen vor Wolkenkratzern und umzuingelt von riesen Frachtschiffen wirkt das Ambiente vorsicht formuliert exentrisch. Die gigantische Shoppingmeile auf der stadtgewandten Seite der Insel und der zugegebenermaßen wunderschöne Übergang vom Festland selbstverständlich ausgestattet mit Rollbändern trüben diesen Eindruck nicht.'},
    {ImageS: 'Brücke am Abend'},
    {Text: 'Dass diese Extravaganz einen gewissen Preis hat, mag man schon erahnen, wenn man einmal von den drakonischen Strafen des Landes gehört hat. Als Tourist merkt man davon aber wenig, auch wenn es hin und wieder ins Auge fällt (Affen füttern 10.000 Singapur-Dollar. Der Punk in mir erlebte einen kurzen Moment der Melancholie, keine Chips zur Hand zu haben).'},
    {ImageH: 'Für dich gibt es nichts, mein Freund!'},
    {Text: 'Präsenter sind Hinweise auf Nachbarschaftswachen, die allgegenwärtige Überwachng und durchgehende Durchsagen an öffentlichen Plätzen oder auf Schildern, auffälliges Verhalten zu melden und Mitmenschen zu denunzieren. Das beginnt bereits bei vergleichsweise harmlosen Missetaten wie dem Kreuzen von Schildkrötenpfaden oder Rauchen an nicht extra dafür vorgesehenen Orten. Mein persönliches Resümee zu Singapur ist deswegen, dass die Stadt definitiv einen Besuch wert ist und die progressive Stadtplanung in vielerlei Hinsicht Vorbild sein sollte. Leben wollte ich dort allerdings nicht.'},
    {ImageS: 'Der angeblich südlichste Punkt Kontinentalasiens'},

];