export const elf = [
    {Title: 'Großstadtgeflüster'},
    {Text: 'Aufgrund der Generosität des Hostelbesitzers konnte ich nach der verspäteten Ankunft noch um kurz vor 1 Uhr Nacht einchecken. Die Fahrt mit der Metro in das Zentrum der Stadt offenbarte bereits einen ersten Eindruck auf das, was mich hier erwartete. Meine optimistische Hoffnung, es doch noch bis 12 ins Hostel zu schaffen, wurde durch eine ewig lange Fahrt aus dem Wasser geblasen; immerhin musste ich durch die halbe Stadt. Reichlich verdaddert von diesem etwas längeren Reisetag und noch etwas mitgenommen vom Wochenende, beschränkte sich mein nächster Tag darauf den notwendigen PCR-Test zu machen, was mehr Zeit in Anspruch nahm als erwartet. Es stellte sich heraus, dass es für unterschiedliche Visa oder andere Einreisevarianten unterschiedliche Anlaufstellen für die Tests gibt. Das muss man sich auch erstmal ausdenken.'},
    {ImageS: 'Angeblich der östliche Rand der Stadt'},
    {Text: 'Der richtige Start fiel deswegen erst auf den zweiten Tag, in dem ich nur mit dem Ziel neue Bücher zu kaufen durch Seoul streifte. Wenig überraschend gibt es hier reichlich Stadt und man stolpert über alle möglichen Paläste, historische Viertel und andere Großstadtkuriositäten. Tierquälerei ist beispielsweise ein riesen Ding in Korea - ich arbeite an einer Fotocollage. Fleischkonsum wird dementsprechend auch groß geschrieben und ich sprach mit mehreren Europäern, die ihren Vegetarismus/Veganismus für die Zeit in Südkorea begraben haben.'},
    {ImageS: 'Asiatische Wasserfälle bleiben eine Enttäuschung'},
    {Text: 'Bücher habe ich übrigens auch bekommen. Das war nicht mehr ganz so einfach, wie in Malaysia oder Thailand, wo die englischsprachige die heimische Literatur dominierte. Generell setzt sich der Eindruck schnell durch, wieder in einem erste Welt Land zu sein. Die eigene Kultur dominiert und englische Hinweise finden höchstens ergänzend statt. Das klappt in manchen Fällen hervorragend (touristische Attraktionen, öffentliche Verkehrsmittel) und in anderen so gar nicht (Restaurants). Insgesamt war ich etwas überrascht, wie wenig die englische Sprache unter weiten Teilen der Gesellschaft nach wie vor verbreitet zu sein scheint. Möglicherweise ist das aber auch eine gewissen Schüchternheit der Koreaner in Bezug auf ihr Schulenglisch zurückzuführen. Scheinbar wird das sehr leblos (vielleicht wie Latein bei uns?) unterrichtet und die Barriere für einen Koreaner Englisch zu lernen ist offensichtlich ohnehin deutlich höher als für einen Europäer.  Bisher auf der Reise war das Niveau auf jeden Fall nur mit dem Hochland in Borneo zu vergleichen. So müssen sich Touristen in Deutschland fühlen.'},
    {ImageS: 'Irgendein Samuraiaufmarsch (oder heißen die nur in Japan so?)'},
    {Text: 'Beim Essen lief es deswegen meistens darauf hinaus, dass ich einigermaßen blind bestellte. Ich verstand die Karte nicht und die Kellner mich nicht und nach einigem Rumzeigen gab es eben das, was man dem Europäer zumuten wollte. Bereut habe ich das bisher noch nie. Das Essen ist fantastisch und insbesondere koreanisches Barbecue eine echte Erfahrung, auch wenn in der Regel haufenweise Dinge vor einem platziert werden, von denen man nur eine entfernte Ahnung hat, was das eigentlich sein könnte oder in welcher Reihenfolge man es essen soll. Nach dem Probieren, weiß man aber in der Regel immerhin zumeist, dass man keine entfernte, sondern schlicht gar keine Ahnung hat, was man da eigentlich isst. Gnadenlos würzig ist in der Regel alles, was definitiv nicht schadet. In Kombination mit meinen überschaubaren Fähigkeiten mit Stäbchen zu essen führt das häufig dazu, dass man sich wie ein kleines Kind fühlt. Wie ein kleines Kind artig einfach alles Aufzuessen war aber eine Taktik, die soweit funktionierte. Allgemein wird Essenskultur in Korea groß geschrieben und es ist üblich häufig außerhalb Essen zu gehen.Während die Preise ansonsten sehr gut mit Deutschland zu vergleichen sind, ist es Restaurant hier vergleichsweise günstig. Ein Umstand den ich gerne in Kauf nehme.'},
    {Text: 'Seoul selbst kennenzulernen ist kinderleicht, weil das Verkehrsnetz exzellent, sehr gut ausgeschildert und super günstig ist. Eine Fahrt kostet in der Regel etwas weniger als 1€ (nur zum Flughafen ist es teurer), was im Anbetracht der Tatsache, dass man gerne mal eine Stunde unterwegs ist, ein echter Schnapper ist. Die T-Money-Card, die man dafür einmalig kauft, lässt sich für Bahn, Bus und Zug aber auch auf diversen Märkten nutzen. Darüberhinaus beschränkt sich das nicht nur auf Seoul, sondern ich werde die Karte auch in anderen koreanischen Städten zum Einsatz bringen können. Die Karte selber habe ich in einem Supermarkt bekommen und bin dabei zum ersten Mal über die für viele Koreaner scheinbar durchaus übliche Obsession für Niedliches gestolpert. Die Karte gab es in vielfacher Ausführung. Auf Rückfrage bestätigte mir die Verkäuferin, dass der einzige Unterschied aber ausschließlich in dem Comictierchen auf der Rückseite der Karte bestände. Ich musste mehrmals insistieren, bevor mir besagte Verkäuferin abnahm, dass es mir aus diesem Grund egal sei, welche der Karten sie mir verkauft. Die  Ungläubigkeit über meine Ignoranz in Bezug auf so eine wichtige Entscheidung war greifbar. '},
    {ImageS: 'Warten auf eine vermutlich sensationelle Boy-Group. Ja, die Schlange war noch deutlich länger und ja, es waren noch viele Stunden bis zum Konzertbeginn.'},
    {Text: 'Ansonsten war es in meinem Hostel relativ einfach andere Leute kennenzulernen und ich habe mir einige Abende mit Deutschen, anderen Europäern oder einem Israeliten um die Ohren geschlagen. Zu sehr ausgeschweift ist das aber zum Glück nie. Man wird ja auch nicht jünger. Außerdem wurden wir einige Tage unterbrochen, in denen die asiatische Regenzeit nach über zwei Monaten selbst einem Ignorantem wie mir klar machen wollte, wie sie zu diesem Titel kam. Unseren Stadtteil erwischte es abgesehen vom Starkregen und abgefahrenen Gewittern nicht besonders dramatisch, aber in Gangnam muss wohl über zwei Tage richtig Land unter gewesen sein, wenn man den Impressionen in sozialen Netzwerken trauen darf. Mit meinem Sonnenschein hat mich also auch die Sonne selbst verlassen… (kling dramatischer als es ist. Mindestens die Hälfte der Zeit war das Wetter fantastisch und kalt ist es hier ohnehin nie um diese Jahreszeit)'},
    {ImageS: 'Mitten in der Stadt. Einfach mal so.'},
    {Text: 'Jetzt gerade sitze ich im (Bullet-)Zug nach Busan. Das heißt man ballert eben in 2 Stunden aus dem Norden in den Süden Koreas an die dortige Küste. Wenn mein Eindruck von Korea weiter so positiv bleibt, könnte ich mir gut vorstellen, hier eine längere Zeit zu verbringen und dem Strandleben zu frönen. Jetzt muss ich aber erstmal rausfinden, wie ich zu meinem nächsten Hostel komme. Bin ja gleich schon da...'}
]