export const zehn = [
    {Title: 'Malaysia, die Zweite'},
    {Text: 'Der erste Eindruck täuschte nicht und wir hatten noch eine hervorragende Abschlusszeit in Malaysia. Kota Kinabalu teilte sich in zwei Phasen auf. Zuerst verbrachten wir ein paar Tage im Hostel und erkundeten unter anderem zwei der fünf Inseln vor der Stadt. Mindestens zwei der Restlichen waren gesperrt, was die Auswahl enorm erleichterte.'},
    {ImageS: 'Gemütlicher Kollege'},
    {Text: 'Jonny verliebte sich in eine vegane Imbissbude und ich bekam meine (Speed-)Bootstour. Der zweite Teil bestand aus einem glücklichen Schnapper, der uns in die Borneo Beach Villas verschlug. Vier Tage Seele baumeln lassen bei bestem Wetter mit Pool vor der Haustür und Balkonblick auf das Meer gaben mir die Gelegenheit ein wenig zu coden und Jonny konnte die unsäglichen Bände sieben und acht (und auch schon 9?) von Game of Thrones abschließen.'},
    {ImageS: 'Der Strand hätte es sich verdient, sich dort häufiger rumzutreiben'},
    {Text: 'Dieser Abschnitt war so dekadent, dass ich es in der Zeit nur zweimal ins eigentlich ganz fantastische Meer dort schaffte - ein grausames Schicksal, aber irgendwie haben wir auch das überstanden. Im Anschluss ging es in die Berge. Das Hochland, um den Kinabalu zeichnet sicher zwar einerseits durch unangenehme Höhe aus, unser erster Aufenthaltsort befand sich fast 2000 Meter über Null, bot dementsprechend aber auch die ein oder andere beeindruckende Aussicht.'},
    {ImageS: 'Keine Gegend, um betrunken nach Hause zu laufen'},
    {Text: 'Dieser Part fühlte sich erstmals richtig nach Reisen an. Wir sahen nun kaum noch andere Touristen, erst recht keine Europäischen und waren im Hostel dort sogar für einige Tage die einzigen Gäste. Englischsprachige Menüs waren die Ausnahme, Bestellen lief manchmal auf Zeichensprache hinaus und das lokale Transportnetz war nur durch Herumfragen und Ausprobieren zu erschließen. Die Preise für Hin- und Rückfahrt zu den heißen Quellen dort vielen dementsprechend signifikant verschieden aus. Die Tour lohnte sich aber dennoch. Immerhin sahen wir einen malaysischen Wasserfall und konnten uns nach Thailand überzeugen, dass nicht unser beider Verständnis dieses Konzepts völlig an der Sache vorbeigeht.'},
    {ImageS: 'Malaysia > Thailand?'},
    {Text: 'Bevor sich heute unsere Wege trennten wartete zum Abschluss noch ein Schmankerl auf uns. Joyce und Birne empfingen uns bei sich zu Hause in Bangkok und wir lebten ein Wochenende wie Gott in Frankreich. Es war feuchtfröhlich (wegen des Pools natürlich), so dass wir den Kopf durchgehend in den Wolken hatten. Nicht nur deswegen ist eine göttliche Analogie mehr als angemessen. Ganz fantastisch war ebenso, nach langer Zeit mal wieder auf Birne zu treffen und alles war sofort wie immer. So muss das sein. Ein bisschen thailändische Kultur erlebten wir auf diese Weise auch noch, als wir von Nachbarn mit Joyce und ihrem Vater in deren Garten eingeladen wurden. Die außerordentlich unbequeme Sitte seine Zeit im Schneidersitz auf dem Boden zu verbringen, nimmt man im Grunde gar nicht war, weil man in atemberaubender Frequenz mit Bier und Früchten nicht nur sprichwörtlich gefüttert wird. Damit geht eine formidable Reisezeit mit Jonny vorbei und ich sitze nun im Flieger nach Seoul und beschäftige mich mit dem Problem, diese Begleitung auch nur ansatzweise adäquat zu ersetzen. Vorerst hoffe ich aber, dass ich nach diversen Verzögerungen wegen des schlechten Wetters (wie immer an Reisetagen) in Bangkok meinen Check-In noch schaffe. Sollte das also der letzte Beitrag bleiben, lebe ich nun in Seoul auf der Straße - was hoffentlich geht, nicht so wie in Singapur.'},
    {ImageS: '"Auf eigenen Infotafeln ablümmeln" fehlt da'}
]