export const vier = [
    {Title: 'Inselruhe'},
    {Text: 'Heute ist unser letzter Tag auf Koh Phangan bevor wir uns in den Nationalpark Khao Soks aufmachen. Jonny erkundigt gerade noch mal ein wenig auf dem Moped die Insel, damit jedenfalls einer irgendwas hier gesehen hat. Ansonsten sind wir uns die Tage auf den Inseln treu gelieben. Dementsprechend ruhe ich gerade auch nur ein wenig vom Ausruhen aus und nutze die Zeit, die wesentlichen Erkenntnisse zusammenzufassen.'},
    {Liste: ['Die Sonne hier ist viel zu krass. Unsere unschuldigen blassen Körper gehen sofort in Flammen auf. Auf der Hinfahrt mit dem Boot habe ich mir in kürzester Zeit das Gesicht verbrannt. Jonny berichtete von diversen Sonnenstichen seinerseits. Unsere Möglichkeiten sind also tagsüber etwas eingeschränkt. Schattenwandeln entwickelt sich zu einer Kunstform.',
            'Nichtstun ist der Knaller. Eigentlich war das vorher auch schon klar, aber unnötige Aktivitäten, Abenteuer, die Welt kennenlernen ist alles vollkommen überberwertet. Ein bisschen Lesen/Programmieren auf einem schattigen Balkon/einer schattigen Terrasse, abgewechselt von Perioden im klimatisierten Zimmer, um abzukühlen - mehr ist für einen runden Tag gar nicht notwendig.',
            'Das Essen ist phänomenal. Sehr würzig und seit wir auf den Inseln sind auch sehr fischlastig hat es uns die Thai-Küche angetan. Letzten Sonntag noch auf Koh Tao haben wir auf einer Dachterasse etwas schicker gegessen. Europäischen Köchen in gehobeneren Einrichtungen wären sicherlicher viele Gründe eingefallen, warum Spear Rips, Garnelen, fantastisch maraninierte Muscheln und ein hervoragendes Stück Rindfleisch nicht Teil eines Gerichts sein sollten, damit sich einzelne Zutateten optimal entfalten. Zum Glück gab es derartige Vorbehalte hier nicht. Direkt um die Ecke gibt es einen Nachtmarkt. Das ist eine ganz nette Angelegenheit mit Livemusik, wo einige Sitzgelegenheiten umzingelt von unterschiedlichen Buden sind, die alles an asiatischer Küche (und Pizza) anbieten, was man sich vorstellen kann. Gestern gab es beispielsweise arabisch. Heute Mittag hatte ich allerdings Spätzle. Wer kann auch ahnen, dass man in einem Restaurant namens "Ratatouille" in Thailand auf einen bayrischen Koch trifft... So phänomenal es ist, so minimalistisch sind allerdings auch die Portionen. Man läuft also den ganzen Tag leicht angehungert durch die Gegend. Kein Wunder, dass die Thai alle so klein sind.',
            'Die Wege auf den Inseln sind teilweise abgefahren. Mit bis zu 300m auf Koh Tao und 600m auf Koh Phangan erreichen die Gipfel gemessen an der überschaubaren Größe der Inseln (und für einen Nordfriesen ja sowieso) ordentliche Höhen. Das wird trotzdem nach Belieben mit Wegen bebaut. Unser Ausflug über Koh Tao hatte definitiv einige abenteuerliche Abschnitte in petto. An einer Stelle war es so steil, dass ich mich einige Meter auf allen Vieren nach unten bewegt habe und dankbar war, dass die Strecke asphaltiert gewesen ist. Dementsprechend ist da auch prompt ein Auto lang gekommen. Unendliches Vertrauen in die Bremsen vorausgesetzt.',
            'Die Ähnlichkeit zu Ostdeutschland ist teilweise frapierend. Unfertige Bauten und überall fliegt Müll rum.',
            'Jonny liebt morning glories.',
            'Ozeane können unerträglich warm werden.',
            'Cocktails kann man hier trinken wie Wasser. Nur auf dem Nachtmarkt waren wir auf einmal etwas angeheitert. Das hat auch direkt zu einem weiteren Ruhetag geführt.',
            'Es gibt nenneswerte Gezeiten. Spürbar allerdings nur an unserem Strand, der vermutlich der hässlichste von ganz Koh Phangan ist.',
            ]
    },
    {ImageS: 'Nachtmarkt bei Tag'},
    {Text: 'Ich fürchte, dass die Zeit der besinnungslosen Ruhe nun eine kleine Unterbrechung erfährt bevor wir nach dem Dschungel vermutlich nach Ko Phi Phi weiterreisen und das Inselleben zum Glück wiederaufnehmen. Derweil hoffe ich von nichts gefressen zu werden.'},
    {ImageS: 'Das Wassser so nah, Abkühlung unerreichbar'}
];