export const fuenfzehn  = [
    {Title: "Segeln"},
    {Text: "Mit dem guten Gefühl im Rücken meinen letzten Flug endlich hinter mich gebracht zu haben, hatte ich Athen vor der Brust. Aversion für die Luft wich der wiederentdeckten Affinität für das Wasser. Einige touristische Aktivitäten und ein Abendessen mit dem ersten Crewmitglied, das ich bei einem formidablen Abendessen kennenlernen durfte, Stefan leiteten eine Woche Segeln ein. Am Folgetag wurde diese Bekanntschaft um Carina, Florian und unseren Skipper Philipp ergänzt. Wir konnten das Boot, das unser Zuhause für die kommende Woche sein sollte, erkunden und unverhofft sprang sogar einer Kabine nur für mich alleine heraus. Darauf folgte gemeinsames Einkaufen, Abendessen und die erste Nacht auf der Yacht."},
    {ImageS: "Wer im Flugzeug nicht ordentlich auf seine Schokolade aufgepasst hatte, musste den Mast hoch."},
    {Text: "Am nächsten Tag erfolgte die Überfahrt auf die andere Seite der Bucht/des Golfes, oder wie auch immer man den Spaß nennt, auf die Insel Poros. Entgegen der Vorhersagen kam kurz vor dem Zielhafen sogar ein wenig Wind auf, so dass der Motor ruhen konnte und richtiges Segeln möglich wurde. Schmetterlinge, Kreuzen, Anluven und andere Dinge, die ich bis heute nicht verstehe, geschahen und ich war mitten drin. Aus der vielseitigen Seglersprache sind eigentlich nur Ankerbier und Piratencola wirklich hängen geblieben. Zu meiner Verteidigung sei aber gesagt, dass wir das auch am meisten geübt haben. Ich könnte noch erwähnen, dass das Abendessen wieder fantastisch war. Das nutzt sich aber schnell ab und sollte sich über die Woche auch nicht ändern. Zusammenfassend ließe sich vielleicht ergänzen, dass ich in einer Woche das gesamte Käsedefizit aus fünf Monaten Asien aufholen konnte. Das war exakt so gut, wie es klingt."},
    {ImageS: "Poros"},
    {Text: "Montag hatten wir einen vergleichsweise kleinen Trip (Schlag?) zurückzulegen. Das ließ Zeit, Poros etwas zu erkunden, diverse Ein- und Ausparkmanöver zu üben und sich ein wenig an Fendern (das sind diese komischen Penüpel, die im Hafen verhindern, das Boote unerwünschten Kontakt zu anderen Booten oder Hafenbecken aufnehmen) festklammernd durch das Meer ziehen zu lassen. Abends liefen wir dann auf Hydra ein. Dort gibt es haufenweise überdimensionale Hauskatzen. Das sind eher Luchse oder so - ungelogen."},
    {ImageH: "Auch Piraten müssen ihre Badesachen mal trocknen"},
    {Text: "Es folgte mit irgendwas um die 60 Seemeilen, wenn mich meine Erinnerung nicht trügt oder ich vielleicht sogar schon involviert genug bin, um Seemannsgarn zu spinnen, unsere längste Tour hinüber auf die Kykladen, konkreter nach Serifos. Da das Wetter wie ohnehin die ganze Woche fantastisch war und Philipp ein schier unermessliches Pensum an Blödsinn, den man auf einem Boot veranstalten kann, aus dem Arm zu schütteln verstand, war aber auch das keine Sekunde langweilig."},
    {ImageS: "Nein, wir haben nicht die einzige Frau an Board für anständige Fotos aus dem Boot gehängt!"},
    {Text: "Am nächsten Tag nahmen wir den Aufstieg in das malerische Bergdörfchen über dem Hafen gelegen in Angriff und deckten uns mit Fisch und Kotelett für das abendliche Grillen ein. Dafür setzten wir nach Kithnos über in eine Bucht in der ein vorgelagerter Teil nur durch einen Strand mit dem Hauptteil der Insel verbunden war. In dessen Schatten grillten wir und machten Lagerfeuer. Klingt ziemlich cool und war es auch. "},
    {ImageS: "Hier schien der Aufstieg noch eine gute Idee"},
    {Text: "So weit, so gut. Nur das Segeln kam bis dato etwas kurz. Für die letzten beiden Tage hatte Erasmus allerdings ganz andere Pläne mit uns. Mit teilweise bis zu 10 Knoten mehr als angekündigt wurden wir aus den Kykladen herausgeblasen. Bei 1 1/2 Meter hohen Wellen und Böen um die 30 Knoten am Steuer zu stehen hat etwas sehr erhabenes und aufregendes an sich - vorausgesetzt es gelingt einem das Geschaukel, die Gischt und die grundsätzliche Gewalt des Meeres auszublenden. Vor Begeisterung schossen wir direkt über das Ziel hinaus und begaben uns in eine windgeschütztere Bucht im Norden des Tempels von Poseidon. Aufgrund dieser Weitsicht unsere Skippers hatten wir trotz des unruhigen Wetters eine gediegene Nacht an Board."},
    {ImageS: "Segeln in den Sonnenaufgang"},
    {Text: "Der letzte Tag begann bereits aufregend mit frühem Aufstehen und einer Fahrt in den Sonnenaufgang. Nach einer Stippvisite bei Poseidons Tempel folgte dann noch eine Menge Segeln. Auch das hatte es mit Böen von bis zu 35 Knoten absolut in sich. Acht Knoten Fahrt mag nicht spannend klingen, hat aber eine ganze andere Dimension, in einem Boot das komplett auf der Seite liegt. Meine Überforderung dabei der überschaubaren Aufgabe, mich um eine einzige Leine zu kümmern, gerecht zu werden, fasst meine Segelfähigkeiten kompakt zusammen. Am frühen Abend trudelten wir dann nach einer fantastischen Woche begeistert, aber auch durchaus erledigt wieder in Athen ein, um das ganze mit einem letzten gemeinsamen Abendessen (ach verdammt…) abzuschließen. Danke an Carina, Stefan, Florian und Philipp für diese wirklich coole Erfahrung. "},
    {Text: "Athen schloss ich mit ein wenig weiterem Sightseeing ab. Meine Pläne, auf die Ruinen von Platons ehemaliger Akademie zu pinkeln, musste ich leider begraben, weil da überraschend viele Kinder spielten. Dass sich in der Hinsicht über die Jahre nichts verschlechtert hat, versöhnte mich aber etwas."},
    {ImageS: "Kleiderordnung a la Moscheen in Malaysia verhinderte Fotos von innen"},
    {Text: "Eine wirklich schöne Zugfahrt brachte mich dann nach Kalabaka und zu den berühmten Meterora-Klöstern - reichlich weiteres rumgekraxel in Bergen und Konfrontation mit meiner Höhenangst also. Nun sitze ich eine malerische Busfahrt durch diverse Bergkämme weiter in einer Hafenbar und warte auf den Beginn meiner nächsten Bootsfahrt. Nur noch drei Wochen…"}
]