export const eins = [
    {Title: 'Die ersten Tage'},
    {Text: 'Eigentlich wollte ich diese Einträge als geile React-Application integrieren, bin aber noch nichts ganz so weit, es sinnvoll umsetzen zu können. Aus technischer Perspektive ist das deswegen nun improvisiert und der zweite Eintrag könnte etwas auf sich warten lassen, bis ich das anständig hinbekomme. Aber zum Eigentlichen:'},
    {Text: 'Nach zwei angenehmen Tagen in Köln bei David bzw. Rita sind Jonas und ich Donnerstagmorgen zusammengekommen und nach Frankfurt gedüst. Die übliche Pimmelei am Flughafen war ereignis-, aber auch problemlos. Das gilt im Grunde auch für den Flug. Nur die letzten 10h haben etwas genervt. Immerhin weiß ich nun, dass Daniel Craig auch in seinem letzten Bond nicht damit aufgehört hat, die Reihe an die Wand zu fahren - in bemerkenswerter Konsequenz. Sean Connery´s Gesicht hätte ich gerne gesehen, als er davon erfuhr, dass sein Alter Ego eines Tages dieSonnenseite von Kondomen nicht mehr zu schätzen wusste...'},
    {Text: 'Abflug war ca. 14 Uhr Ortszeit in Frankfurt und Ankunft kurz nach 6 Uhr Ortszeit in Bangkok. Das ließ uns mit dem Dilemma zurück, zu Tagesbeginn gut ins Bett gehen zu können. Das Jetlag bekamen wir aber eigentlich recht zügig in den Griff. Ich mit etwas kürzeren Nächten und Jonny mit 12h-Nächten. Alle Wege führen nach Rom.'},
    {Text: 'Es ist zwar ein leidiges Thema, aber trotzdem ein Wort zum Wetter: Nachdem mir Angst und Bange vor dem Klimaschock Bangkok gemacht wurde, muss ich anerkennen, dass das sicherlich nicht ohne ist, schlimmer als Münster im Sommer allerdings auch nicht. Es ist zwar etwas wärmer und drückender, aber dafür gibt es hin und wieder Wind. Im Gegensatz zu Münster lohnt Schwitzen also.'},
    {Text: 'Die ersten beiden Tage haben wir in der Altstadt gepennt. Da ist alles voller Attraktionen und Touristen. Vor Begeisterung haben wir direkt vergessen das Hostel zu verlängern und sind nun in Chinatown.'},
    {ImageS: 'Der Ausblick von der Dachterasse unseres neuen Hostels. Ganz nett eigentlich.'},
    {Text: 'In der Altstadt war aber auch nichts alles schlecht. Vor Allem für das leckere Essen und die Cocktailpreise brauchten wir kaum Gewöhnungszeit. Außerdem haben die Thai in Erwartung unserer Ankunft erstmal den Geburtstag ihrer Königin gefeiert und legalisieren nächste Woche sogar Marihuanna. Trotzdem ist es unmöglich nicht schnell zur Kenntnis zu nehmen, dass man zum großen Preis in einem Spiel, zu dem man eigentlich nicht gehört, geworden ist. Selbst hartgesottene Turbokapitalisten wie wir, ausgestattet mit all der Selbstgerechtigkeit, die unser Leben voller Anerkennung und Lobhudelei mit sich bringt für Dinge, für die man in der Regel nach Abzug aller Privilegien kaum etwas kann, waren dieser Aufmerksamkeit schnell überdrüssig. So ist die überbordende Freundlichkeit und Aufmerksamkeit, mit der man in hoher Frequenz die Fahrt zur nächsten Touristenattraktion, eine Mahlzeit oder ab einer gewissen Uhrzeit Ping-Pong angeboten bekommt, für manche vielleicht schmeichelhaft, sicherlich als Teil der thailändischen Kultur zu begreifen, in erster Linie aber verdammt unangenehm.'},
    {Text: 'In Chinatown ist es in dieser Hinsicht zum Glück etwas ruhiger, auch wenn hier noch mehr Menschen unterwegs zu sein scheinen. Wir können also etwas ungestörter die Stadt erkunden bevor wir in ein paar Tagen weiterziehen werden.'},
    {Text: 'Aus irgendeinem Grund schreibe ich diese Zeilen direkt in Note und es gibt dementsprechend keine Rechtschreibkorrektur... Zum Glück muss ich den Mist nicht lesen.'}
];