export const sechs = [
    {Title: 'Der Dschungel'},
    {Text: 'Dieser Beitrag stand in meinem Kopf eigentlich schon bevor wir überhaupt Khao Sok erreichten. Wenn ich mich schon den unsäglichen Gefahren des Dschungels aussetzen sollte, wollte ich zumindest meine kleine Plattform nutzen, um den Rest der aufgeklärten Welt in diesem überschaubaren Rahmen vor dieser Hölle zu warnen. Und tatsächlich bewahrheiteten sich viele meiner Sorgen. Das Klima war drückend, alle Insekten dieser Welt leben dort und alle haben Bock auf dein Blut, ich hab mir Leeches von den Beinen gepult und bin Spinnen, deren Körper so groß wie meine Faust waren, so nah gekommen, dass ich mir dieser Größenordnungen auch absolut sicher sein konnte. Krank wurde ich auch. Das war allerdings nicht der Dschungel, sondern idiotische Briten, die es für eine gute Idee hielten, die Klimaanlage auf 18 Grad zu stellen. Trotzdem war diese Woche sonderbarerweise auch ziemlich cool. Ein Teil von mir bedauerte letztendlich sogar, den König des Dschungels nie leibhaftig erlebt zu haben. Ein anderer wesentlich rationalerer Teil kriegt sich deswegen überhaupt nicht mehr ein, weil ich in dieser Woche Tigern in freier Wildbahn definitiv  näher gekommen bin, als es jemals eine sinnvolle Idee sein kann.'},
    {Text: 'Aber von vorne weg: Sonntag verließen wir Koh Phangan mit dem Schiff und sind in kleinen Bussen nach Kaoh Sok kutschiert worden. Das war wahnsinnig chaotisch, weil man an scheinbar willkürlichen Streckenabschnitten das Gefährt wechseln musste und teilweise Leute mit dem gleichen Ziel in unterschiedliche Karren geleitet wurden. Aber sobald man sich der Führung der Thailänder hingab und den Versuch aufgab nennenswerte Kontrolle zu erhalten, war es eigentlich ganz charmant. In Khao Sok haben wir am ersten Tag den Nationalpark direkt vor der Hütte auf eigene Faust erforscht. Anfangs entspannte Waldwege wurden später etwas abenteuerlicher, weswegen wir das gesteckte Ziel nicht ganz erreichen konnten und zwei "Wasserfälle" (in Thailand ist alles, was ein wenig sprudelt und wo dementsprechend Wasser zumindest für einen kurzen Moment in die Verlegenheit kommen könnte zu fallen, ein Wasserfall).'},
    {ImageH: 'Eindeutig ein Wasserfall'},
    {Text: 'Die beiden Affen, die direkt am Eingang zum Nationalpark über uns hinwegtobten, blieben aber die einzige aufregende Entdeckung. Am Dienstag haben wir uns dann einem der Trips angeschlossen, die dort in Masse und Klasse unters fahrende Volk (ist es "too much" diejenigen, die Unterhalten werden und nehmen, und nicht mehr die, die unterhalten und geben, zum fahrenden Volk unserer Zeit zu erklären?) gebracht werden. Dazu gehörte zuerst, mit dem Boot über den gewaltigen künstlich angelegten See im Nationalpark zu brettern. Obwohl unser Boot einige Knoten auf die Piste brachte, waren wir bestimmt 1 1/2 - 2h unterwegs.'},
    {ImageH: 'Stand offensichtlich auch mal höher das Wasser'},
    {Text: 'Dann gab es auf einer Schwimminsel Gelegenheit, die angespannte Blase zu beruhigen, Essen zu fassen und ein wenig zu baden. Die allgegenwärtige Präsenz des Dschungels hatte so nie Gelegenheit zu drückend zu werden. Nach dieser kleinen Phase der Entschleunigung unternahmen wir eine kleine Wanderung. Das Kind in mir, war davon schwer begeistert. Der steinige Untergrund von Passagen durchs Wasser führte dazu, dass sie nicht Barfuß zu bewältigen waren und Schuhe und Beine durchgehend entweder vollständig nass (zum ersten Mal in Thailand auch kühl!) oder eingeschlammt waren. Ganz fantastisch. Das Highlight war dann eine kleine Höhlenwanderung/-beschwimmung, für die wir aufgrund von Jonnys Insistenz - Cui honorem, honorem! - glücklicherweise mit Kopflampen ausgerüstet waren. Am Ende konnte man einzeln ein kleines Stück zu einem Wasserfall (thailändischer Wasserfall) schwimmen. Der Legende nach soll das Baden in diesem Wasser einem Menschen eine Woche Lebenszeit schenken. Was für ein Glück, dass wir uns genau dem Trip angeschlossen haben, der uns gerade zu diesem Wasserfall gebracht hat! Im Endeffekt aber ein fairer Deal, weil wir so die Woche Lebenszeit, die uns die Strapazen eines langen Tages kosteten, zurückbekamen.'},
    {Text: 'Diese Strapazen in Kombination mit Sonnenbrand und der einsetzenden Erkältung haben mich am nächsten Tag dann aber so außer Gefecht gesetzt, dass ich sogar eine kurze Malaria-Paranoia unterhalten habe. Immerhin konnte ich das Delirium nutzen, um den vorigen Text zu schreiben und wir konnten noch zwei ruhige Tage in Kaoh Sok einstreuen. Übrigens war das Thai-Food dort meiner Meinung nach bis jetzt am Besten und Abseits von Bangkok und den Inseln tatsächlich auch mal spottgünstig. Jonny hat es trotzdem in beeindruckender Manier bewältigt eine Woche lange an dem Mojito für 80 Bat vorbeizuschlendern und erst gestern am Strand von Ko Phi Phi wieder zugeschlagen - für 180 Bat.'},
    {Text: 'Apropos Ko Phi Phi. Da sind wir mittlerweile angekommen und ohne zu viel vorwegzunehmen, das Klima hier ist vielversprechend. Außerdem gibt es auch ein richtiges Meer mit Salz, Wind und Abkühlung und nicht so eine unangenehme Strebersee wie auf Koh Tao in bundstiftblau, in der man bei 10 Meter Tiefe noch den Boden sehen kann.'},
    {Text: 'Disclaimer: Ich habe den Nationalpark die ganze Zeit "Dschungel" geschimpft, aber das ist nicht korrekt. In Thailand gibt es keinen Primärdschungel mehr und selbst darüber hinaus sollte man sich wohl keiner Illusion unterwerfen, dass die paar Meter, die wir sahen, irgendetwas anderes als vom Menschen für den Menschen vorbereiteter Abenteuerurlaub sind.'},
    {ImageS: 'Ko Phi Phi'}
];