export const dreizehn  = [
    {Title: "Stippvisite in Vietnam"},
    {Text: 'Nach der relativen Ruhe Koreas folgte nun Vietnam. Was für das ungeübte Auge wie Chaos erscheint, ist vermutlich unvergleichliche Liebe fürs Detail. Das beginnt schon mit der Sprache. Wie wir beim shippern in Ha Long Bay lernten, steht beispielsweise das „Ha“ -  selbstverständlich immer mit irgendwelchen Betonungsstrichen - bereits für drei unterschiedliche Worte. In „Hanoi“ steht es für den Fluss. Die Stadt ging ursprünglich nicht über das zentrale Delta umgeben vom roten Fluss hinaus. In Ha Long Bay für hinuntersteigend (Der landende Drache, der aus der Hauptstadt (damals noch Thang Long - aufsteigender Drache - und nicht Hanoi) auf der Landmasse landete, wo sich nun die Bucht befindet, sie zerstörte, damit Vietnam gegen irgendwelche Invasoren verteidigte und so Ha Long Bay schuf, wie es heute existiert). „Thang" ist allerdings nicht das einzige Wort, dass für aufsteigend stehen kann, sondern ebenfalls „Ha“. Es ist bekanntlich immer guter Stil Gegensätze gleich zu benennen und damit ist das auch nur für uns Ignoranten unverständlich. '},
    {ImageS: 'Ha Long Bay: Weltkulturerbe, Wunder der Natur, Touristen-Swimmingpool'},
    {Text: "Das gleiche gilt für den berühmt-berüchtigten Verkehr in Hanoi, der durchaus hält, was er verspricht. Man gewöhnt sich aber schnell daran und registriert nach einiger Zeit sogar eine gewisse Sanftheit im vermeintlichen Chaos. Die Abwesenheit offensichtlicher Regeln führt zu einer sehr hohen Achtsamkeit aller Teilnehmer und so lange man sich eindeutig verhält wird man mühelos zum Teil des Flows. Zugegebenermaßen klingt das aber etwas entspannter als es war. Die niemals still stehende Metallmasse auf größeren Straßen zu überwinden, war bis zum Ende aufregend."},
    {ImageH: "So viele Motorräder wie hier Fische sind in auf den Straßen Hanois auf dem gleichen Raum"},
    {Text: "Interessant ist dabei auch die mühelose Verständigung der Einheimischen. Und kommuniziert wird durchgehend. Einmal Hupen beispielsweise bedeutet „Hallo, Ich fahre, Du fährst, Tschüss, Hier bin ich, einen Hot Dog mit frischen Zwiebeln aber ohne Gurken bitte, nichts und Vorsicht: Aquaplaning. Das ist bekannt und dementsprechend funktioniert die Kommunikation auch lückenlos und trotz der Vielzahl an Verkehrsteilnehmern kommt es seltener zu Stillstand als man meinen würde. "},
    {ImageS: "Kobra für das Herz, Kräuter für den Rücken, Früchte für die Beine. Alles für die Gesundheit"},
    {Text: "Neben Kreuzfahrten und Großstadtsafaris verbrachte ich noch einen Tag in Ninh Binh, einer Provinz im Süden von Hanoi. Tolle Landschaften, alte Kaiser in Särgen und der übliche Schman. Das Touristenherz frohlockte."},
    {ImageS: "Auch im Jenseits wird Bier geschätzt"},
    {Text: "Ein bisschen aufregender war mein Trip für ein paar Tage aufs Land. In dem Ferienort, der üblicherweise eher ein Ziel für Einheimische im Somme ist, war außerhalb der Saison komplett tote Hose und niemand sprach englisch. Das stimmt allerdings nicht ganz. Interessanterweise konnte man hier die Früchte der politischen Bemühungen der Landes beobachten (nicht dass meine selektive Wahrnehmung und die mehr als kleine Kontrollgruppe, tatsächlich ein ernstzunehmender Indikator wären). Den Tourismus im Land aufzupeppeln, wird insbesondere dadurch vorangetrieben, dass viele Englischlehrer rekrutiert werden. Wir sprachen bereits in Thailand mit Reisenden, die nach Vietnam wollten, um dort zu unterrichten. Dementsprechend waren es die Kinder, die unter den stolzen Augen ihrer Eltern, zu dem Sonderling aus dem Westen geschickt wurden, um in ihrem durchaus passablen Englisch herauszufinden, was ich denn Essen möchte oder, ob ich mit auf einen Kaffee dazusetzen möchte. Nicht unbedingt einfach, wenn man sich nicht versteht, aber immerhin mag ich keinen Kaffee. "},
    {ImageS: "Tourismus nach Corona: Die goldverzierte Fassade hält nicht mehr lückenlos"},
    {Text: "Aufgrund der großen Fürsorge der Bewohner dort, wäre es sicherlich möglich gewesen, mit viel Geduld und Handzeichen irgendwie den Rückweg in die englischsprachige Welt anzutreten. Allerdings wurde ich nach zwei Tage meiner Rolle als Attraktion dann doch etwas überdrüssig (immerhin bin ich der Urlauber und will Attraktionen begaffen und nicht andersherum) und löste die Situation wie ein guter Westeuropäer, indem ich einfach Geld auf das Problem schmiss. "},
    {ImageS: "Irgendeine Höhle"}

]