export const zwoelf = [
    {Title: "Hinnamnor und anderes Flüchtiges"},
    {Text: "Optimistisch nun auch meine letzten zwei Leser verloren zu haben, scheint der richtige Moment gekommen zu sein, mal wieder ein wenig Unsinn zum Besten zu geben. Heute bin ich seit einem Monat in Busan und die Zeit verging wie im Flug. Es fühlt sich auch nicht so an, als wäre ich nur an einem Ort gewesen. Dafür ist die Stadt zu weitläufig, ich war in zu vielen unterschiedlichen Hostels und habe meine Zeit mit zu vielen verschiedenen Menschen verbracht. Höchste Zeit also den Ball wieder etwas flacher zu halten, um Zeit und Energie für die wichtigen Dinge im Leben zu sparen. Ich fürchte, im letzten Monat habe ich so gut wie gar nicht gelesen, an Sport war nicht zu denken und möglicherweise habe ich keinen einzigen Blogeintrag verfasst."},
    {ImageS: "Frühstück im Schwimmbad"},
    {Text: "Ein wichtiger Grund dafür ist der Strand. Falls irgendjemand der Illusion unterlegen war, dass ich ein Tourist für spannende Abenteuer und aufregendes Sightseeing sei, ... weit gefehlt. Spätestens jetzt ist etabliert, dass ich ein „geil-den-ganzen-Tag-am-Strand-rumliegen“-Urlauber bin und das geht hier ganz fantastisch. Insbesondere mit dem Ende der Badesaison im August sind auch die Stadtstrände richtig attraktiv geworden. Um so charmanter ist es, dass man von meinem aktuellen Hostel aus quasi zu einem dieser besagten Strände spucken kann. In der Badesaison selber, waren diese Aufenthalte noch ein wenig unangenehm, da, sobald man es wagte das Wasser tiefer als bis zum Bauchnabel zu betreten, Strandgäste von mindestens zwei aufgeregten Bademeistern zur Rechenschaft gepfiffen wurden mit allem, was ihre Trillerpfeifen hergaben. Die Koreaner scheinen ein zögerliches Verhältnis zum Wasser zu haben und ohne Privatarmee an Life Guards sind die Stände seit Septemberbeginn auch nicht mehr so überlaufen. Ein Umstand, den ich selbstverständlich mit Kusshand hinnehme. "},
    {ImageS: "Foto von Fotografierenden"},
    {Text: "Allgemein ist der Strand für Koreaner (nein, nicht alle… ich habe ganz viele, tolle Koreaner kennengelernt mit denen man jede Menge Blödsinn machen konnte. Es muss doch noch möglich sein für den Spaß an der Freude ein wenig zu generalisieren auch wenn wir nun den Biedermeier mit Beginn der 20er Jahre vollends ausgerufen haben…) nur Mittel zum Zweck. Der Koreaner ist nie wirklich am Strand. Strand und Meer dienen als Hintergründe für Familienerinnerungen, Hochzeitsfoto und vor Allem Instagram. Das Ausmaß dabei ist wirklich abgefahren. Man stolpert von einem Fotoshooting in das nächste. Einerseits gibt das Hoffnung, dass unsere Kultur uns aus welchen Gründen auch immer möglicherweise etwas resilienter gegen das vollständige Abtauchen in einer digitalen Identität, was man übrigens hier nicht nur am Strand beobachten kann, machte. Andererseits ist die Befürchtung vermutlich deutlich angebrachter, dass uns das Schlimmste einfach noch bevorsteht."},
    {ImageS: "BBQ"},
    {Text: "Der zweite wichtige Grund ist, dass man in den Hostels haufenweise Leute kennenlernt, die nahezu alle jünger sind und dementsprechend auch jeden Tag in Kneipen oder Clubs rennen können. Oft genug schaffe ich es mich dem zu entziehen, aber nicht immer. Ein großer Vorteil ist dabei, dass Menschen mit mir erstaunlich gut zurechtzukommen scheinen, solange sie mich nicht so gut verstehen. Das wiederum ist eine logische Folge meines überschaubaren Englisch und dementsprechend kann man sich einfach von den seichten Freuden der Oberflächlichkeit treiben lassen. Meinen koreanischen Freund von Jeju-Island hat das allerdings leider nicht davon abgehalten, die ganze Wikinger-Geschichte zu ernst zu nehmen. Daher ist noch unklar, ob ich meine Ehre als Nordmann wahren kann, ohne auf lebendigem Octopus rumzukauen. Ich hoffe das beste und befürchte das schlimmste…"},
    {ImageS: "Die Ruhe vor dem Sturm (und vor Trillerpfeifen, die mich vom Stand jagten)"},
    {Text: "Übrigens war hier noch ein Typhoon. Das ganze wurde natürlich heißer gekocht als gegessen. Zugegebenermaßen hatte der Sturm, als er das Festland morgens traf, aber genügend Bums, dass nicht mal die Leichtsinnigkeit einiger zuvor genossener(?) Sojus dazu verleiten konnte, uns dem lange an der frischen (aber zugigen) Luft auszusetzen. Als ich ein paar Stunden später wieder aufgestanden bin, war das ganze Nummer aber auch schon vorbei und warmer Sonnenschein begrüßte mich. "},
    {ImageS: "Nach dem Sturm"},
    {Text: "Ansonsten habe ich wohl die vermutlich erste gute Einleitung in die Philosophie gelesen, die mir bisher untergekommen ist. „Nasty, Brutish and Short“ von Scott Hershovitz liefert eine Einführung in viele der größeren Themen des Fachs und verzichtet dabei fast vollständig auf eitlen Fachjargon. Mit Hilfe seiner Kinder bestreitet er diese Herausforderung und sieht sich dadurch mit der Notwendigkeit konfrontiert, den gegeben Fragen tatsächlich auf den Grund zu gehen, ohne seine immer weiter nachhakenden Sprösslinge mit Plattitüden abspeisen zu können. Ich stimme dabei nicht mit all seinen Auffassungen überein (insbesondere in Bezug auf Spitzensport) und das Körper-Geist-Problem ist selbst gut aufgearbeitet gähnend langweilig, aber ich konnte so zur Abwechslung mal etwas über Philosophie lernen. Und Dissens ist ja eigentlich auch der halbe Spaß."},
    {Text: "Mir bleiben nun noch 11 Tage zum Runterfahren bevor der letzte Teil meiner Reise beginnt. Danach werde ich mich dann wieder den unbequemen Fragen des Lebens stellen müssen. Beispielsweise, was macht man denn zum Abendessen, wenn man nicht in ein Restaurant geht?"}
]
    
