export const neun = [
    {Title: 'Malaysia, die Erste'},
    {Text: 'Unser erstes Ziel im dritten und letzten Land unserer gemeinsamen Reise war für Jonny und mich Melaka. Die Stadt im Süden des Landes ist von Singapur bequem per Bus zu erreichen und zeichnet sich durch eine reiche Geschichte zur Kolonialzeit aus. Einer der Zugänge zur zentral gelegenen St. Pauls Kirche soll beispielsweise eines der ältesten noch erhaltenen europäischen Gebäude in Asien sein. Richtig bedacht ist das irgendwie ein weird flex, da selbst das offensichtlich nicht besonders alt ist.'},
    {ImageS: 'Geschmackvolles posieren für Insta neben Totentafeln'},
    {Text: 'Gestartet sind wir aber erstmal entspannt nach der Aufregung Singapur im Hotel mit Pool etwas abseits des Zentrums. Vermutlich wegen Umbaumaßnahmen war das super günstig und wir konnten uns jeglicher touristischer Verpflichtung erfolgreich für drei Tage entziehen.'},
    {ImageS: 'Pool mit Ausblick'},
    {Text: 'Der riesige, halb fertig gebaute Gebäudekomplex im Hintergrund ist übrigens eine durchaus typische Erscheinung für Malaysia und inbesondere Melaka. In diesem Fall kursierte die Spekulation, dass auf dieser Halbinsel im großen Stil Geld gewaschen wurde und sie deswegen nun tapeziert mit halbfertigen Bauprojekten ist. Auch Corona dürfte dem touristisch im Vergleich zu beispielsweise Thailand noch in den Kinderschuhen steckenden Land übel zugesetzt haben. Neben nicht abgeschlossen Bauprojekten sind geschlossene Restaurants keine Seltenheit. Unser erster Versuch ein Hostel zu buchen für den zweiten Teil unseres Aufenthalts in der Stadt, endete dementsprechend auch vor einem Geisterladen. Die Buchung wurde noch begeistert per automatisierter Mail bestätigt, laut Auskunft der Nachbarn war das Hostel selbst aber schon seit mindestens zwei Jahren geschlossen. Anzeige steht, Hostelworld! Der Notfallladen, in dem wir dann untergekommen sind, war aber auch eine sehr gute Wahl. Aus dem Zentrum, um die Jonker-Street und ihr geschäftiges Treiben, heraus haben wir uns direkt einer Fahrradtour - eine sehr interessante Erfahrung im malaysischen Verkehr - zurück in den einzigen uns bekannten Teil der Stadt auf erwähnte Halbinsel angeschlossen. Die Moschee dort war zum Sonnenuntergang durchaus ein Hingucker, das Grundstück, wie bei allen anderen Moscheen auch, für uns aber unzugänglich, weil der vorgeschriebene Klamottenkodex in diesem Urlaub nicht mehr erfüllt wird. Allgemein ist der Islam in Malaysia sehr präsent und die institutionell koordinierte Ruhestörung durch Lautsprecher verstärkter Gebete steht unseren Kirchentürmen in nichts nach. Eine Party-Religion scheint hier der einzige Ausweg, um ein eigenes Stück vom Kuchen zu bekommen. Ruhestörung für alle dank Religionsfreiheit quasi. Der anschließende Umtrunk als Belohnung für die erfolgreiche Fahrradfahrt, lag auf der Hand und nachdem wir uns in Singapur auf Serben reduzierten, lernten wir so in Malaysia erfolgreich Singapurer kennen.'},
    {ImageH: 'Vermaledeite Kameraeinstellungen. Das sollte ein Selfie werden...'},
    {Text: 'Obligatorische Bootstour und reichhaltige Erkundigung des kulinarischen Angebots des Zentrums schlossen die restlichen Tage in Melaka dann für uns ab, bevor wir nach Kuala Lumpur (ab jetzt angepasst an die Geflogenheiten der Einwohner - und aus Swag - nur noch KL genannt) weiterreisten. KL ist definitiv angenehmer als Bangkok. Dass aufgrund einer Promotion die Metro bis auf den letzten Tag für Umme war, hat auch nicht geschadet. Dafür ist zumindest das Zentrum, in dem wir uns überwiegend aufhielten, preislich auch eher mit Singapur zu vergleichen. Trotzdem ist die Stadt verhältnismäßig grün und oft gibt es sogar Bürgersteige. Parks sind im Gegensatz zu Bangkok zugänglich, aber unser einziger Versuch einen zu betreten scheiterte am saftigen Preis. Die Anlage um die Petronas-Tower ist dafür definitiv einen Besuch wert und das schlendern durch die Stadt zeichnet sich allgemein durch viele interessante kleine und im Fall der Tower sehr große Impressionen aus.'},
    {ImageS: 'KL´s Phallussymbol'},
    {Text: 'Eine kleinere Bahnfahrt in den Norden der Stadt brachte uns zu den wohl berühmten Batu Caves. Das kann man sich aber tatsächlich auch einfach auf Google angucken. Die Grotte an sich ist in 5 Minuten erkundet. Die höhe des Steilen Aufstiegs wurde zumindest aber von mir signifikant unterschätzt und erst fast oben angekommen erkannt. Der Abstieg war dementsprechend unangenehm.'},
    {ImageS: 'Phallussymbol der Batu-Caves'},
    {Text: 'Die restlichen gemeinsamen zwei Wochen werden wir zum Abschluss auf Borneo verbringen und nach haufenweise kleinen Affen nun vielleicht auch mal große Affen angucken. Die drittgrößte Insel der Erde teilen sich die Länder Malaysia, Indonesien und Brunei. Wir werden allerdings nur ein wenig den Norden erkunden. "Sein statt reisen" lautet nach wie vor das Motto. Der erste Eindruck könnte zumindest schon schlechter sein. Das Hostel in dem wir untergekommen sind, ist mit Bar auf der Dachterasse und hervorragenden Gemeinschaftsräumen, in denen ich mich beim Schreiben dieses Textes gerade herumlümmel, geradezu luxuriös ausgestattet und das alles - na klar - zum ganz kleinen Preis.'}
];